version: '3.8'

services:
  php:
    container_name: php-contacts
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 9000:9000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-contacts
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - app-network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql-contacts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: